server:
  addrs:
    - http: '0.0.0.0:40772'
channels:
  # 愛知県
  - name: ＴＯＫＹＯ　ＭＸ
    type: GR
    channel: '16'
  - name: ＣＢＣテレビ
    type: GR
    channel: '18'
    isDisabled: false
  - name: 中京テレビ
    type: GR
    channel: '19'
    isDisabled: false
  - name: ＮＨＫ総合
    type: GR
    channel: '20'
    isDisabled: false
  - name: フジテレビ
    type: GR
    channel: '21'
  - name: ＴＢＳ
    type: GR
    channel: '22'
  - name: テレビ東京
    type: GR
    channel: '23'
  - name: テレビ朝日
    type: GR
    channel: '24'
  - name: 日テレ
    type: GR
    channel: '25'
  - name: ＮＨＫＥテレ・東京
    type: GR
    channel: '26'
  - name: ＮＨＫ総合・東京
    type: GR
    channel: '27'
tuners:
  - name: adapter0
    types: [GR]
    command: >-
      dvbv5-zap -a 0 -c ./config/dvbconf-for-isdb/conf/dvbv5_channels_isdbt.conf
      -r -P <channel>